CRYP-81: Header, Footer and Application layout
Cryptoaxus/Cryptoaxus-Armup-Frontend pull request #1
Opened 2023-06-23 13:53 UTC by Shahzaib864

## Jira

https://softaxus-jira.atlassian.net/browse/CRYP-81

## Changes

- Added application structure
- Worked on adding following features to the layout
-  Header
- Logo
Search NFT, Artist, Collection
Explore
Stats
Blogs
Network(Currency DropDown)
Profile
Login Button

-> Footer

Logo
Social Links
Explore
Stats
Blog
My Profile
My Collection
Careers 
About 
Subscription

## Testing

- https://softaxus-jira.atlassian.net/browse/CRYP-81?focusedCommentId=10129

2023-06-26 20:12 UTC, junaid-softaxus commented on src/components/LandingPage/landingPage.js
> +                <h1 className="Heading">Explore, Collect, and Sell  NFTs</h1>
Please remove this dummy data.

2023-06-26 20:12 UTC, junaid-softaxus commented on src/components/LandingPage/landingPage.js
> +                <h1 className="Heading">Explore, Collect, and Sell  NFTs</h1>
Remove this dummy data.

2023-06-26 20:15 UTC, junaid-softaxus commented on src/components/LandingPage/landingpage.css
> +.Heading {
The class name should always start in lowercase.

2023-06-26 20:16 UTC, junaid-softaxus commented on src/components/LandingPage/landingpage.css
The file name should be `landingPage.css` instead of `landingpage.css`.

2023-06-26 20:18 UTC, junaid-softaxus commented on src/assets/Images/ARMNFT.png
1. The `Images` folder name should be `images`.
2. The file name should be `armNft.png` instead of `ARMNFT.png`

2023-06-26 20:19 UTC, junaid-softaxus commented on src/assets/Images/CurrencyIcon/ethereum-1.svg
Folder names should be camel case.

2023-06-26 20:19 UTC, junaid-softaxus commented on src/assets/Images/Icons/ARMNFT_logo -Footer.svg
See my comments above for the folder and file naming.

2023-06-26 20:19 UTC, junaid-softaxus commented on src/assets/Images/Icons/Facebook.svg
See my comments above for the folder and file naming.

2023-06-26 20:19 UTC, junaid-softaxus commented on src/assets/Images/Icons/Hamburger .svg
See my comments above for the folder and file naming.

2023-06-26 20:19 UTC, junaid-softaxus commented on src/assets/Images/Icons/Instagram.svg
See my comments above for the folder and file naming.

2023-06-26 20:20 UTC, junaid-softaxus commented on src/assets/Images/Icons/Youtube.svg
See my comments above for the folder and file naming.

2023-06-26 20:20 UTC, junaid-softaxus commented on src/assets/Images/Icons/search-normal.svg
See my comments above for the folder and file naming.

2023-06-26 20:20 UTC, junaid-softaxus commented on src/assets/Images/Icons/user.svg
See my comments above for the folder and file naming.

2023-06-26 20:20 UTC, junaid-softaxus commented on src/assets/Images/Logo/ARMNFT_logo 1.svg
See my comments above for the folder and file naming.

2023-06-26 20:20 UTC, junaid-softaxus commented on src/assets/Style/style.css
See my comments above for the folder and file naming.

2023-06-26 20:21 UTC, junaid-softaxus commented on src/components/shared/footer/footer.css
> +}
See my comment above for the class naming convention.

2023-06-26 20:22 UTC, junaid-softaxus commented on src/components/shared/header/header.js
> +                </svg>
Make sure the code is aligned correctly.

2023-06-26 20:23 UTC, junaid-softaxus commented on src/components/shared/header/header.js
> +                </svg>
Fix code alignment.

2023-06-26 20:23 UTC, junaid-softaxus commented on src/components/shared/header/header.js
> +                    <path d="M10 7h4v10h-4zm2-5a7 7 0 1 0 7 7 7 7 0 0 0-7-7z"></path>
Code alignment.

2023-06-26 20:23 UTC, junaid-softaxus commented on src/components/shared/header/header.js
Code alignment needs to be fixed.

2023-06-26 20:24 UTC, junaid-softaxus reviewed
Address the feedback.

2023-06-27 10:58 UTC, Shahzaib864 reviewed
camel case use in whole application.

2023-06-27 11:39 UTC, junaid-softaxus commented
@Shahzaib864 The folders name is still the same. Please update the names and use lower case in this regard.

2023-06-27 11:42 UTC, junaid-softaxus requested changes
Folders name and images name should be updated and must be in lower case.

2023-07-06 16:54 UTC, junaid-softaxus approved these changes
Reviewed

2023-07-06 16:55 UTC, merged